let state={page:'discover',mode:'image',lang:'zh',visual:{composition:[],lighting:[],style:[]},mainImage:'',refs:['','','',''],activeRef:0,assetView:'grid'};
const $=id=>document.getElementById(id); const $$=q=>[...document.querySelectorAll(q)];
function toast(t){$('status').textContent=t;$('status').classList.add('show');setTimeout(()=>$('status').classList.remove('show'),1500)}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function go(page){state.page=page;$$('.page').forEach(p=>p.classList.toggle('active',p.id==='page-'+page));$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.page===page));window.scrollTo({top:0,behavior:'smooth'});if(page==='assets')renderAssets();if(page==='share')renderShareSelect();}
$$('[data-page]').forEach(b=>b.onclick=()=>go(b.dataset.page));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
function getAssets(){try{return JSON.parse(localStorage.getItem('promptStudioCN.assets.v02')||'[]')}catch{return[]}}
function setAssets(a){localStorage.setItem('promptStudioCN.assets.v02',JSON.stringify(a));renderAssets();renderShareSelect();updateStats()}
function updateStats(){$('statTemplates').textContent=TEMPLATES.length;$('statModels').textContent=MODELS.length;$('statAssets').textContent=getAssets().length}
function assetCard(a,local=false){let cover=a.imageData?`<img src="${a.imageData}" alt="">`:`<div class="fake-art">${a.emoji||({image:'◉',video:'🎬','3d':'🧊',audio:'♪'}[a.type]||'✦')}</div>`;return `<article class="card asset-card" data-detail="${esc(a.id)}" data-local="${local?'1':'0'}"><div class="cover ${a.cover||'c1'}">${cover}<span class="cover-badge">${MODE_DATA[a.type]?.label||a.type}</span>${a.time?`<span class="cover-time">${a.time}</span>`:''}</div><div class="asset-body"><div class="asset-title">${esc(a.name)}</div><div class="asset-desc">${esc(a.desc||a.subject||'本地 Creation Asset')}</div><div class="mini-tags">${(a.tags||[]).slice(0,3).map(t=>`<span class="mini-tag">${esc(t)}</span>`).join('')}</div><div class="asset-meta"><span>${esc(a.model||'—')}</span><span>${local?'本地资产':esc(a.template||'')}</span></div></div></article>`}
function renderFeatured(){ $('featuredGrid').innerHTML=FEATURED.slice(0,4).map(a=>assetCard(a)).join(''); $('galleryGrid').innerHTML=FEATURED.map(a=>assetCard(a)).join(''); bindDetails(); }
function bindDetails(){$$('[data-detail]').forEach(el=>el.onclick=()=>{let local=el.dataset.local==='1';let a=local?getAssets().find(x=>String(x.id)===el.dataset.detail):FEATURED.find(x=>x.id===el.dataset.detail);if(a)showDetail(a,local)})}
function showDetail(a,local){$('modalTitle').textContent=a.name;$('modalBody').innerHTML=`<div class="detail-grid"><div class="detail-preview">${a.imageData?`<img src="${a.imageData}">`:(a.emoji||({image:'◉',video:'🎬','3d':'🧊',audio:'♪'}[a.type]||'✦'))}</div><div><div class="kv"><div>类型</div><div>${MODE_DATA[a.type]?.label||a.type}</div><div>模型</div><div>${esc(a.model||'—')}</div><div>模板</div><div>${esc(a.preset||a.template||'—')}</div><div>标签</div><div>${(a.tags||[]).join(' · ')||'—'}</div></div><div class="sep"></div><b>说明</b><p class="muted">${esc(a.desc||'这是一个本地 Creation Asset，可继续编辑 Prompt、参数和效果案例。')}</p>${a.prompt?`<b>Prompt</b><div class="codebox" style="min-height:120px;margin-top:7px">${esc(a.prompt)}</div>`:''}<div class="card-actions">${local?'<button class="btn primary" id="editLocalAsset">载入 Builder</button>':'<button class="btn primary" id="forkFeatured">使用此模板</button>'}<button class="btn" id="closeFromBody">关闭</button></div></div></div>`;$('detailModal').classList.add('show');$('closeFromBody').onclick=closeModal;if(local)$('editLocalAsset').onclick=()=>{loadAsset(a);closeModal()};else $('forkFeatured').onclick=()=>{let t=TEMPLATES.find(x=>x.name===a.template);if(t)applyTemplate(t);closeModal()};}
function closeModal(){$('detailModal').classList.remove('show')}$('modalClose').onclick=closeModal;$('detailModal').onclick=e=>{if(e.target===$('detailModal'))closeModal()};
function renderGallery(){let q=$('gallerySearch').value.toLowerCase(),type=$('galleryType').value;let list=FEATURED.filter(a=>(type==='all'||a.type===type)&&(`${a.name} ${a.desc} ${a.tags.join(' ')}`).toLowerCase().includes(q));$('galleryGrid').innerHTML=list.map(a=>assetCard(a)).join('')||'<div class="empty">没有匹配的效果资产。</div>';bindDetails()}
$('gallerySearch').oninput=renderGallery;$('galleryType').onchange=renderGallery;
function renderVisual(){ $$('[data-opts]').forEach(box=>{let key=box.dataset.opts;box.innerHTML=VISUAL[key].map(([name,ico])=>`<div class="vopt ${state.visual[key].includes(name)?'selected':''}" data-vkey="${key}" data-vname="${name}"><div class="vpic">${ico}</div><div class="vname">${name}</div></div>`).join('')});$$('[data-vkey]').forEach(v=>v.onclick=()=>{let arr=state.visual[v.dataset.vkey],name=v.dataset.vname;let i=arr.indexOf(name);i>=0?arr.splice(i,1):arr.push(name);renderVisual();updatePrompt()})}
function renderBuilderSelects(){let d=MODE_DATA[state.mode];$('modelSelect').innerHTML=d.models.map(x=>`<option>${x}</option>`).join('');$('presetSelect').innerHTML=d.presets.map(x=>`<option>${x}</option>`).join('');$('builderModeBadge').textContent=d.label+'模式';$('metaMode').textContent=d.label;['image','video','3d','audio'].forEach(m=>$(m==='3d'?'threeDControls':m+'Controls')?.classList.toggle('hidden',m!==state.mode));if(state.mode==='image')$('imageControls').classList.remove('hidden');else $('imageControls').classList.add('hidden');updatePrompt()}
function setMode(m){state.mode=m;$$('#modeTabs .tab').forEach(t=>t.classList.toggle('active',t.dataset.mode===m));renderBuilderSelects()}
$$('#modeTabs .tab').forEach(t=>t.onclick=()=>setMode(t.dataset.mode));$$('[data-quick]').forEach(b=>b.onclick=()=>{setMode(b.dataset.quick);go('builder')});
function promptZH(){let s=$('subjectInput').value.trim()||`使用「${$('presetSelect').value}」模板创建内容`;let parts=[s];if(state.mode==='image'){if(state.visual.composition.length)parts.push('构图：'+state.visual.composition.join('、'));if(state.visual.lighting.length)parts.push('光线：'+state.visual.lighting.join('、'));if(state.visual.style.length)parts.push('风格：'+state.visual.style.join('、'));}
 if(state.mode==='video'){if($('motionSubject').value.trim())parts.push('主体动作：'+$('motionSubject').value.trim());parts.push('摄影机运动：'+$('cameraMotion').value);parts.push('镜头：'+$('lens').value);parts.push('运动速度：'+$('motionSpeed').value);parts.push('镜头时长：'+$('duration').value+'，画幅：'+$('aspect').value);if($('envMotion').value.trim())parts.push('环境 / 时间变化：'+$('envMotion').value.trim());if($('firstState').value.trim())parts.push('开始状态：'+$('firstState').value.trim());if($('lastState').value.trim())parts.push('结束状态：'+$('lastState').value.trim());if($('audioDesc').value.trim())parts.push('声音 / 对白：'+$('audioDesc').value.trim())}
 if(state.mode==='3d')parts.push(`3D输出：${$('meshType').value}，拓扑：${$('topology').value}，材质：${$('material').value}`);if(state.mode==='audio')parts.push(`音频类型：${$('audioType').value}，情绪：${$('audioMood').value}，速度：${$('bpm').value}`);if($('extraInput').value.trim())parts.push('补充参数：'+$('extraInput').value.trim());if($('negativeInput').value.trim())parts.push('禁止 / 避免：'+$('negativeInput').value.trim());parts.push('目标模型：'+$('modelSelect').value);return parts.join('\n\n')}
function promptEN(){let s=$('subjectInput').value.trim()||`Create content using the ${$('presetSelect').value} preset.`;let parts=[s];if(state.mode==='image'){if(state.visual.composition.length)parts.push('Composition: '+state.visual.composition.join(', '));if(state.visual.lighting.length)parts.push('Lighting: '+state.visual.lighting.join(', '));if(state.visual.style.length)parts.push('Style: '+state.visual.style.join(', '));}if(state.mode==='video'){if($('motionSubject').value.trim())parts.push('Subject motion: '+$('motionSubject').value.trim());parts.push('Camera motion: '+$('cameraMotion').value);parts.push('Lens: '+$('lens').value);parts.push('Motion speed: '+$('motionSpeed').value);parts.push('Duration: '+$('duration').value+', aspect ratio: '+$('aspect').value);if($('envMotion').value.trim())parts.push('Environmental / temporal motion: '+$('envMotion').value.trim());if($('firstState').value.trim())parts.push('First state: '+$('firstState').value.trim());if($('lastState').value.trim())parts.push('Last state: '+$('lastState').value.trim());if($('audioDesc').value.trim())parts.push('Audio / dialogue: '+$('audioDesc').value.trim())}if(state.mode==='3d')parts.push(`3D output: ${$('meshType').value}; topology: ${$('topology').value}; material: ${$('material').value}`);if(state.mode==='audio')parts.push(`Audio type: ${$('audioType').value}; mood: ${$('audioMood').value}; pace: ${$('bpm').value}`);if($('extraInput').value.trim())parts.push('Additional parameters: '+$('extraInput').value.trim());if($('negativeInput').value.trim())parts.push('Avoid: '+$('negativeInput').value.trim());parts.push('Target model: '+$('modelSelect').value);return parts.join('\n\n')}
function updatePrompt(){$('promptOutput').textContent=state.lang==='zh'?promptZH():promptEN();$('metaModel').textContent=$('modelSelect').value||'—';$('metaPreset').textContent=$('presetSelect').value||'—';if(localStorage.getItem('promptStudioCN.autosave')!=='off')saveDraft()}
$$('#page-builder input,#page-builder textarea,#page-builder select').forEach(x=>x.addEventListener('input',updatePrompt));$$('[data-lang]').forEach(b=>b.onclick=()=>{state.lang=b.dataset.lang;$$('[data-lang]').forEach(x=>x.classList.toggle('active',x===b));updatePrompt()});
function fileToData(file,cb){let r=new FileReader();r.onload=()=>cb(r.result);r.readAsDataURL(file)}$('mainUploader').onclick=()=>$('mainFile').click();$('mainFile').onchange=e=>{let f=e.target.files[0];if(f)fileToData(f,d=>{state.mainImage=d;$('mainPreview').src=d;$('mainPreview').classList.remove('hidden');updatePrompt()})};$$('#refStrip .thumb').forEach(t=>t.onclick=()=>{state.activeRef=+t.dataset.ref;$('refFile').click()});$('refFile').onchange=e=>{let f=e.target.files[0];if(f)fileToData(f,d=>{state.refs[state.activeRef]=d;let t=$(`#refStrip .thumb[data-ref="${state.activeRef}"]`);t.innerHTML=`<img src="${d}">`;toast('参考图已加入')})};
function snapshot(){return {id:Date.now(),name:$('assetName').value.trim()||'未命名创作资产',type:state.mode,lang:state.lang,model:$('modelSelect').value,preset:$('presetSelect').value,subject:$('subjectInput').value,negative:$('negativeInput').value,extra:$('extraInput').value,visual:JSON.parse(JSON.stringify(state.visual)),imageData:state.mainImage,refs:[...state.refs],prompt:state.lang==='zh'?promptZH():promptEN(),video:{motionSubject:$('motionSubject').value,cameraMotion:$('cameraMotion').value,lens:$('lens').value,motionSpeed:$('motionSpeed').value,duration:$('duration').value,aspect:$('aspect').value,envMotion:$('envMotion').value,firstState:$('firstState').value,lastState:$('lastState').value,audioDesc:$('audioDesc').value},threeD:{meshType:$('meshType').value,topology:$('topology').value,material:$('material').value},audio:{audioType:$('audioType').value,audioMood:$('audioMood').value,bpm:$('bpm').value},created:new Date().toISOString(),version:'0.2'}}
function saveAsset(){let a=getAssets();a.push(snapshot());try{setAssets(a);toast('已保存到本地资产库')}catch(e){toast('保存失败：浏览器本地容量可能不足')}}$('builderSave').onclick=saveAsset;
$('copyPrompt').onclick=async()=>{try{await navigator.clipboard.writeText($('promptOutput').textContent);toast('Prompt 已复制')}catch{toast('浏览器阻止了剪贴板访问')}};
function downloadObj(obj,name){let blob=new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),500)}$('builderExport').onclick=()=>downloadObj(snapshot(),($('assetName').value.trim()||'creation-asset')+'.aipack.json');
function resetBuilder(){state.visual={composition:[],lighting:[],style:[]};state.mainImage='';state.refs=['','','',''];$('subjectInput').value='';$('negativeInput').value='';$('extraInput').value='';$('assetName').value='未命名创作资产';$('mainPreview').classList.add('hidden');$('refStrip').querySelectorAll('.thumb').forEach((t,i)=>t.textContent='+ Ref '+String.fromCharCode(65+i));renderVisual();updatePrompt()}$('builderReset').onclick=resetBuilder;
function applyTemplate(t){setMode(t.type);$('presetSelect').value=t.preset||$('presetSelect').value;$('subjectInput').value=t.subject||'';$('negativeInput').value=t.negative||'';state.visual={composition:[...(t.composition||[])],lighting:[...(t.lighting||[])],style:[...(t.style||[])]};$('assetName').value=t.name;renderVisual();updatePrompt();go('builder');toast('模板已载入')}
