function renderTemplates(){let q=$('templateSearch').value.toLowerCase(),type=$('templateType').value,list=TEMPLATES.filter(t=>(type==='all'||t.type===type)&&(`${t.name} ${t.desc} ${t.tags.join(' ')}`).toLowerCase().includes(q));$('templateGrid').innerHTML=list.map(t=>`<article class="card template-card"><div class="template-icon">${t.icon}</div><span class="badge">${MODE_DATA[t.type].label}</span><h3>${esc(t.name)}</h3><p>${esc(t.desc)}</p><div class="compat">${t.tags.map(x=>`<span class="mini-tag">${x}</span>`).join('')}</div><div class="card-actions"><button class="btn sm primary" data-use-template="${t.id}">使用模板</button><button class="btn sm" data-view-template="${t.id}">查看</button></div></article>`).join('');$$('[data-use-template]').forEach(b=>b.onclick=()=>applyTemplate(TEMPLATES.find(t=>t.id===b.dataset.useTemplate)));$$('[data-view-template]').forEach(b=>b.onclick=()=>showTemplate(TEMPLATES.find(t=>t.id===b.dataset.viewTemplate)))}
function showTemplate(t){$('modalTitle').textContent=t.name;$('modalBody').innerHTML=`<div class="detail-grid"><div class="detail-preview">${t.icon}</div><div><span class="badge accent">${MODE_DATA[t.type].label}</span><p class="muted">${esc(t.desc)}</p><div class="kv"><div>默认模板</div><div>${esc(t.preset)}</div><div>标签</div><div>${t.tags.join(' · ')}</div></div><div class="sep"></div><b>核心 Prompt 结构</b><div class="codebox" style="margin-top:7px;min-height:110px">${esc(t.subject)}</div><div class="card-actions"><button class="btn primary" id="modalUseTemplate">使用模板</button></div></div></div>`;$('detailModal').classList.add('show');$('modalUseTemplate').onclick=()=>{applyTemplate(t);closeModal()}}
$('templateSearch').oninput=renderTemplates;$('templateType').onchange=renderTemplates;$$('[data-template-open]').forEach(b=>b.onclick=()=>{let t=TEMPLATES.find(x=>x.id===b.dataset.templateOpen);if(t)showTemplate(t)});
function renderModels(){let q=$('modelSearch').value.toLowerCase(),type=$('modelType').value,list=MODELS.filter(m=>(type==='all'||m.type===type)&&(`${m.name} ${m.desc} ${m.abilities.join(' ')}`).toLowerCase().includes(q));$('modelGrid').innerHTML=list.map(m=>`<article class="card model-card"><div class="model-icon">${({image:'🖼',video:'🎬','3d':'🧊',audio:'♪'}[m.type])}</div><span class="badge">${MODE_DATA[m.type].label}</span><h3>${esc(m.name)}</h3><p>${esc(m.desc)}</p><div class="compat">${m.abilities.map(x=>`<span class="mini-tag">${x}</span>`).join('')}</div><div class="asset-meta"><span>${esc(m.vendor)}</span><button class="btn sm" data-model-start="${m.name}" data-type="${m.type}">用此模型创作</button></div></article>`).join('');$$('[data-model-start]').forEach(b=>b.onclick=()=>{setMode(b.dataset.type);$('modelSelect').value=b.dataset.modelStart;updatePrompt();go('builder')})}
$('modelSearch').oninput=renderModels;$('modelType').onchange=renderModels;
function renderWorkflows(){$('workflowGrid').innerHTML=WORKFLOWS.map((w,i)=>`<article class="card workflow-card"><span class="badge ${i<2?'accent':''}">${w[1]}</span><h3>${w[0]}</h3><p>${w[2]}</p><div class="compat">${w[3].map(x=>`<span class="mini-tag">${x}</span>`).join('')}</div><div class="card-actions"><button class="btn sm primary" data-wf="${i}">打开预览</button><button class="btn sm">复制结构</button></div></article>`).join('');$$('[data-wf]').forEach(b=>b.onclick=()=>{$('modalTitle').textContent=WORKFLOWS[+b.dataset.wf][0];let w=WORKFLOWS[+b.dataset.wf];$('modalBody').innerHTML=`<p class="muted">${w[2]}</p><div class="codebox" style="min-height:100px">${w[3].map((x,i)=>`${i+1}. ${x}`).join('\n↓\n')}</div><p class="small" style="margin-top:12px">V0.2 只保存工作流结构。后续可加入节点参数、ComfyUI workflow.json 和运行状态。</p>`;$('detailModal').classList.add('show')})}
function renderAssets(){let list=getAssets(),q=($('assetSearch')?.value||'').toLowerCase(),type=$('assetType')?.value||'all';list=list.filter(a=>(type==='all'||a.type===type)&&(`${a.name} ${a.model} ${a.preset} ${a.subject}`).toLowerCase().includes(q));$('assetsGrid').innerHTML=list.length?list.slice().reverse().map(a=>assetCard({...a,desc:a.subject,tags:[a.preset||'',a.type]},true)).join(''):'<div class="empty">还没有本地资产。进入构建器创建第一个 Creation Asset。</div>';$('assetTableBody').innerHTML=list.slice().reverse().map(a=>`<tr><td><div class="row-cover">${a.imageData?`<img src="${a.imageData}">`:'✦'}</div></td><td><b>${esc(a.name)}</b></td><td>${MODE_DATA[a.type]?.label||a.type}</td><td>${esc(a.model)}</td><td>${esc(a.preset)}</td><td>${new Date(a.created).toLocaleString()}</td><td><button class="btn sm" data-row-load="${a.id}">载入</button> <button class="btn sm danger" data-row-del="${a.id}">删除</button></td></tr>`).join('');bindDetails();$$('[data-row-load]').forEach(b=>b.onclick=()=>loadAsset(getAssets().find(a=>a.id==b.dataset.rowLoad)));$$('[data-row-del]').forEach(b=>b.onclick=()=>deleteAsset(b.dataset.rowDel));updateStats()}
function loadAsset(a){setMode(a.type||'image');state.lang=a.lang||'zh';state.visual=a.visual||{composition:[],lighting:[],style:[]};state.mainImage=a.imageData||'';state.refs=a.refs||['','','',''];$('modelSelect').value=a.model||$('modelSelect').value;$('presetSelect').value=a.preset||$('presetSelect').value;$('subjectInput').value=a.subject||'';$('negativeInput').value=a.negative||'';$('extraInput').value=a.extra||'';$('assetName').value=a.name||'未命名创作资产';if(a.video){Object.entries({motionSubject:'motionSubject',cameraMotion:'cameraMotion',lens:'lens',motionSpeed:'motionSpeed',duration:'duration',aspect:'aspect',envMotion:'envMotion',firstState:'firstState',lastState:'lastState',audioDesc:'audioDesc'}).forEach(([k,id])=>{if(a.video[k]!=null)$(id).value=a.video[k]})}if(a.threeD){$('meshType').value=a.threeD.meshType;$('topology').value=a.threeD.topology;$('material').value=a.threeD.material}if(a.audio){$('audioType').value=a.audio.audioType;$('audioMood').value=a.audio.audioMood;$('bpm').value=a.audio.bpm}if(state.mainImage){$('mainPreview').src=state.mainImage;$('mainPreview').classList.remove('hidden')}else $('mainPreview').classList.add('hidden');$('refStrip').querySelectorAll('.thumb').forEach((t,i)=>t.innerHTML=state.refs[i]?`<img src="${state.refs[i]}">`:'+ Ref '+String.fromCharCode(65+i));renderVisual();updatePrompt();go('builder');toast('资产已载入')}
function deleteAsset(id){let a=getAssets().filter(x=>x.id!=id);setAssets(a);toast('资产已删除')}
$('assetSearch').oninput=renderAssets;$('assetType').onchange=renderAssets;$$('.view-toggle button').forEach(b=>b.onclick=()=>{state.assetView=b.dataset.view;$$('.view-toggle button').forEach(x=>x.classList.toggle('active',x===b));$('assetsGrid').classList.toggle('hidden',state.assetView!=='grid');$('assetsList').classList.toggle('hidden',state.assetView!=='list')});
function renderShareSelect(){let a=getAssets();$('shareAssetSelect').innerHTML=a.length?a.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join(''):'<option value="">暂无本地资产</option>'}
function selectedShare(){return getAssets().find(a=>String(a.id)===$('shareAssetSelect').value)}$('downloadShare').onclick=()=>{let a=selectedShare();if(!a)return toast('请先创建一个本地资产');downloadObj(a,(a.name||'asset')+'.aipack.json')};$('makeShareCode').onclick=()=>{let a=selectedShare();if(!a)return toast('请先选择资产');$('shareCode').textContent=btoa(unescape(encodeURIComponent(JSON.stringify(a))));};$('copyShareCode').onclick=async()=>{try{await navigator.clipboard.writeText($('shareCode').textContent);toast('分享码已复制')}catch{toast('无法访问剪贴板')}};
function importAssetObj(obj){if(!obj||!obj.name)return toast('文件不是有效 Creation Asset');let a=getAssets();obj.id=Date.now();obj.created=new Date().toISOString();a.push(obj);setAssets(a);toast('资产已导入')}
$('importDrop').onclick=()=>$('shareFile').click();$('shareFile').onchange=e=>readJSONFile(e.target.files[0],importAssetObj);$('importCodeBtn').onclick=()=>{try{let obj=JSON.parse(decodeURIComponent(escape(atob($('importCode').value.trim()))));importAssetObj(obj)}catch{toast('分享码格式无效')}};
function readJSONFile(file,cb){if(!file)return;let r=new FileReader();r.onload=()=>{try{cb(JSON.parse(r.result))}catch{toast('JSON 文件格式错误')}};r.readAsText(file)}
$('assetsImportBtn').onclick=()=>$('assetImportFile').click();$('assetImportFile').onchange=e=>readJSONFile(e.target.files[0],obj=>{Array.isArray(obj)?setAssets([...getAssets(),...obj.map(x=>({...x,id:Date.now()+Math.random()}))]):importAssetObj(obj)});$('assetsExportAll').onclick=()=>downloadObj(getAssets(),'prompt-studio-cn-assets-backup.json');
function saveDraft(){let d=snapshot();d.imageData='';d.refs=[];localStorage.setItem('promptStudioCN.draft',JSON.stringify(d))}
function saveSettingsObj(){let s={lang:$('defaultLang').value,mode:$('defaultMode').value};localStorage.setItem('promptStudioCN.settings',JSON.stringify(s));toast('设置已保存')}$('saveSettings').onclick=saveSettingsObj;$$('.toggle').forEach(t=>t.onclick=()=>{t.classList.toggle('on');if(t.dataset.setting==='autosave')localStorage.setItem('promptStudioCN.autosave',t.classList.contains('on')?'on':'off')});$('backupBtn').onclick=()=>downloadObj({assets:getAssets(),settings:JSON.parse(localStorage.getItem('promptStudioCN.settings')||'{}')},'prompt-studio-cn-full-backup.json');$('restoreBtn').onclick=()=>$('restoreFile').click();$('restoreFile').onchange=e=>readJSONFile(e.target.files[0],obj=>{if(obj.assets)setAssets(obj.assets);if(obj.settings)localStorage.setItem('promptStudioCN.settings',JSON.stringify(obj.settings));toast('备份已恢复')});$('wipeAll').onclick=()=>{if(confirm('确定清空本地资产、草稿与设置？')){localStorage.removeItem('promptStudioCN.assets.v02');localStorage.removeItem('promptStudioCN.draft');localStorage.removeItem('promptStudioCN.settings');renderAssets();toast('本地数据已清空')}};
$('newTemplateBtn').onclick=()=>toast('V0.3：支持自定义模板编辑器');$('newWorkflowBtn').onclick=()=>toast('V0.3：支持可编辑节点工作流');
function init(){renderFeatured();renderVisual();renderBuilderSelects();renderTemplates();renderModels();renderWorkflows();renderAssets();renderShareSelect();updateStats();let s=JSON.parse(localStorage.getItem('promptStudioCN.settings')||'{}');if(s.lang){state.lang=s.lang;$('defaultLang').value=s.lang}if(s.mode)$('defaultMode').value=s.mode;}
init();
